name: shackleton-linux-ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Get App version
        uses: mikefarah/yq@master
        with:
          cmd: echo "VERSION=$(yq .version pubspec.yaml)" >> $GITHUB_ENV
      - name: "Push version tag from pubspec.yaml"
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ env.VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: false
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev libmpv-dev libmpv2 binutils coreutils desktop-file-utils fakeroot fuse libgdk-pixbuf2.0-dev patchelf python3-pip python3-setuptools squashfs-tools strace util-linux zsync
      - run: flutter config --enable-linux-desktop
      - run: flutter create --platforms=linux .
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run flutter_launcher_icons
      - run: flutter build linux --release --no-tree-shake-icons
      - uses: AppImageCrafters/build-appimage-action@master
        with:
          recipe: "AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|hobleyd|shackleton|latest|*x86_64.AppImage.zsync
          VERSION: ${{ env.VERSION }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: shackleton-${{ env.VERSION }}
          files: Shackleton-${{ env.VERSION }}-x86_64.AppImage
          tag_name: ${{ env.VERSION }}
